### ISSUE TITLE
Add Polybius Square Cipher

### ISSUE THREAD

**Issue by jmeline** [jmeline/Cyphers#9]
https://www.braingle.com/brainteasers/codes/polybius.php

**Comment by GF1977** [comment]
I will take this issue

**Comment by cordeirossauro** [comment]
@GF1977 Are you writing it in C#? If so, I would like to do it in Python.

**Comment by cordeirossauro** [comment]
Great, if it is possible, I want to do it in Python :+1:

**Comment by jmeline** [comment]
I'm fine with it. :)

**Comment by cordeirossauro** [comment]
Sent my code on PR #35 :+1: :
